version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: music_postgres_db
    ports:
      - "5556:5432"
    environment:
      POSTGRES_DB: "bd_backend_nest2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin12345"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: