###
GET http://127.0.0.1:3000/users
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc0MGQwN2Q2LTQ3ZDQtNDhlNS05N2Y5LTgzZWQxYmU5ZTdkNyIsImVtYWlsIjoibWFlbEBtYWlsLmNvbSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzODI4NjIyLCJleHAiOjE3NTM4MzIyMjJ9.qpWCtJu29wB7PLpR93smdcB9_KWygHOXnospZ4rdhwI

### reemplazar rol por otro
PATCH  http://127.0.0.1:3000/users/b0757148-d393-4ad9-8873-309830a743bb/role/replace
Content-Type: application/json

{
    "removeId": "33f44553-e360-406e-95f4-ba2c02c37fe6",
    "addId": "60bb0178-ce6f-4535-ae85-3ff66e068fb6"
}

### Guardar usuario

POST http://127.0.0.1:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc0MGQwN2Q2LTQ3ZDQtNDhlNS05N2Y5LTgzZWQxYmU5ZTdkNyIsImVtYWlsIjoibWFlbEBtYWlsLmNvbSIsInJvbGVzIjpbXSwiaWF0IjoxNzUzODI4NjIyLCJleHAiOjE3NTM4MzIyMjJ9.qpWCtJu29wB7PLpR93smdcB9_KWygHOXnospZ4rdhwI

{
    "username": "mela",
    "email": "mela@mail.com",
    "password": "mael1234"
}

### Guardar usuario con roles


POST http://127.0.0.1:3000/users
Content-Type: application/json

{
  "username": "ema00",
  "email": "ema003@empresa.com",
  "password": "12345786",
  "isActive": true,
  "roleIds": [ "33f44553-e360-406e-95f4-ba2c02c37fe6"]
}

### Guardar perfil completo

POST http://127.0.0.1:3000/persona/completar-perfil/a5402db0-caad-4bdd-bb68-65d570a31315
Content-Type: application/json

{
    "nombres": "blastils",
    "apellidos": "blastil",
    "ci_dni": "123456",
    "fecha_nacimiento": "2025-07-12",
    "genero": "masculino",
    "telefono": "78123778"
}




### mostrar usuario por id

GET http://127.0.0.1:3000/users/59fe6769-c092-4ac3-9cac-bc792928106a

### modificar un usuario por id

PATCH http://127.0.0.1:3000/users/554cb492-213e-4438-bca5-50a8d54aecc3
Content-Type: application/json

{
    "username": "minaa",
    "email": "minaa@mail.com",
    "password": "mina1234"
}

### Eliminar

DELETE http://127.0.0.1:3000/users


### Eliminar rol de un usuario

PATCH http://127.0.0.1:3000/users/699fe6bb-757f-4067-adf3-4c44c3598dfa/role/remove
Content-Type: application/json

{
    "roleIds": ["60bb0178-ce6f-4535-ae85-3ff66e068fb6"]
}



